services:
  - type: web
    name: srushti-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        fromService:
          type: web
          name: srushti-backend
          envVarKey: RENDER_EXTERNAL_HOSTNAME
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: srushti-db
          property: connectionString
  
  - type: static_site
    name: srushti-frontend
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: srushti-db
    databaseName: srushti
    user: srushti
